### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by curtiola** [crilleaz/PikaBot#1]
does "incense and lucky egg bypasser" mean that even if i have none, it will constantly have the effects of both?

**Comment by crilleaz** [comment]
Most bots when using either egg's or incense, it gets registered and you'll get a soft-ban, by sending different packets, it bypasses the check and your account will not get banned.

**Comment by curtiola** [comment]
ah, very helpful, thank you! i'll give PikaBot a try then :) do you need to update it since they changed the API?

**Comment by crilleaz** [comment]
We are trying to figure out the new API, Mobo the creator of most bypasser's is already working on it! As soon as we get a working one, it will get updated!

**Comment by curtiola** [comment]
awesome, thanks, i'll keep an eye out for updates then :D
